version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tradeflow-db
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: tradeflow-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/.env.common
      - .env.local
    depends_on:
      - db
    restart: on-failure
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

volumes:
  db_data: