version: "3.9"

services:
  app:
    image: ${APP_IMAGE:-ghcr.io/denikandil/tradeflow-trade-service:latest}
    container_name: tradeflow-app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-9090}:9090"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  db:
    image: mysql:8.0
    container_name: tradeflow-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data:
