"""Update LastPriceInfo schema to match current model

Revision ID: 071e9705e4d0
Revises: bec897393293
Create Date: 2025-04-28 22:59:58.891978

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "071e9705e4d0"
down_revision = "bec897393293"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("last_price_info", sa.Column("last_price", sa.Float(), nullable=True))
    op.add_column(
        "last_price_info", sa.Column("change_today", sa.Float(), nullable=True)
    )
    op.add_column(
        "last_price_info",
        sa.Column("change_today_percentage", sa.Float(), nullable=True),
    )
    op.add_column(
        "last_price_info",
        sa.Column("market_identifier", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "last_price_info",
        sa.Column("provider_source", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "last_price_info",
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.alter_column(
        "last_price_info",
        "ticker",
        existing_type=mysql.VARCHAR(length=10),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_last_price_info_ticker"), "last_price_info", ["ticker"], unique=True
    )
    op.drop_column("last_price_info", "atr")
    op.drop_column("last_price_info", "last_closed_price")
    op.drop_column("last_price_info", "source")
    op.drop_column("last_price_info", "deleted_at")
    op.drop_column("last_price_info", "created_at")
    op.drop_column("last_price_info", "rsi")
    op.drop_column("last_price_info", "sma")
    op.drop_column("last_price_info", "last_fetched_price")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "last_price_info",
        sa.Column("last_fetched_price", mysql.FLOAT(), nullable=False),
    )
    op.add_column("last_price_info", sa.Column("sma", mysql.FLOAT(), nullable=True))
    op.add_column("last_price_info", sa.Column("rsi", mysql.FLOAT(), nullable=True))
    op.add_column(
        "last_price_info",
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "last_price_info", sa.Column("deleted_at", mysql.DATETIME(), nullable=True)
    )
    op.add_column(
        "last_price_info",
        sa.Column("source", mysql.VARCHAR(length=100), nullable=False),
    )
    op.add_column(
        "last_price_info", sa.Column("last_closed_price", mysql.FLOAT(), nullable=True)
    )
    op.add_column("last_price_info", sa.Column("atr", mysql.FLOAT(), nullable=True))
    op.drop_index(op.f("ix_last_price_info_ticker"), table_name="last_price_info")
    op.alter_column(
        "last_price_info",
        "ticker",
        existing_type=sa.String(length=20),
        type_=mysql.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.drop_column("last_price_info", "last_updated")
    op.drop_column("last_price_info", "provider_source")
    op.drop_column("last_price_info", "market_identifier")
    op.drop_column("last_price_info", "change_today_percentage")
    op.drop_column("last_price_info", "change_today")
    op.drop_column("last_price_info", "last_price")
    # ### end Alembic commands ###
