"""Add deleted_at column for soft deletes

Revision ID: 1e7d56c319d5
Revises: 6a069f95395e
Create Date: 2025-03-10 21:34:37.272283

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1e7d56c319d5"
down_revision = "6a069f95395e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades",
        "trade_type",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "trades",
        "source",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=100),
        nullable=True,
    )
    op.alter_column(
        "trades",
        "transaction_type",
        existing_type=mysql.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "trades",
        "ticker",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "trades", "unrealized_holdings", ["holding_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trades", type_="foreignkey")
    op.alter_column(
        "trades",
        "ticker",
        existing_type=sa.String(length=10),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "trades",
        "transaction_type",
        existing_type=mysql.VARCHAR(length=10),
        nullable=False,
    )
    op.alter_column(
        "trades",
        "source",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "trades",
        "trade_type",
        existing_type=sa.String(length=50),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
