"""Add total buy/sell fields to UnrealizedHolding

Revision ID: 84f6ae5a3865
Revises: 071e9705e4d0
Create Date: 2025-05-05 20:30:14.310733

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "84f6ae5a3865"
down_revision = "071e9705e4d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "unrealized_holdings",
        sa.Column("total_buy_quantity", sa.Float(), nullable=True, server_default="0"),
    )
    op.add_column(
        "unrealized_holdings",
        sa.Column("total_buy_cost", sa.Float(), nullable=True, server_default="0"),
    )
    op.add_column(
        "unrealized_holdings",
        sa.Column("total_sell_quantity", sa.Float(), nullable=True, server_default="0"),
    )
    op.add_column(
        "unrealized_holdings",
        sa.Column("total_sell_value", sa.Float(), nullable=True, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("unrealized_holdings", "total_sell_value")
    op.drop_column("unrealized_holdings", "total_sell_quantity")
    op.drop_column("unrealized_holdings", "total_buy_cost")
    op.drop_column("unrealized_holdings", "total_buy_quantity")
    # ### end Alembic commands ###
