"""Add realized PnL columns to holdings

Revision ID: bec897393293
Revises: 48f096597be3
Create Date: 2025-04-28 22:09:53.968242

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bec897393293"
down_revision = "48f096597be3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new columns (nullable)
    op.add_column(
        "unrealized_holdings", sa.Column("realized_pnl", sa.Float(), nullable=True)
    )
    op.add_column(
        "unrealized_holdings",
        sa.Column("realized_pnl_percentage", sa.Float(), nullable=True),
    )
    # Remove the data backfilling SQL execution from the migration
    # The backfilling should be done by a separate script (e.g., scripts/recalculate_holdings.py)
    # after the migration is applied.
    # conn = op.get_bind()
    # conn.execute(...)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("unrealized_holdings", "realized_pnl_percentage")
    op.drop_column("unrealized_holdings", "realized_pnl")
    # ### end Alembic commands ###
