"""Refactor unrealized_holdings table fields

Revision ID: dc3ec5003c90
Revises: efa53c2719ad
Create Date: 2025-03-09 21:51:03.946072

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "dc3ec5003c90"
down_revision = "efa53c2719ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades",
        "trade_type",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "trades",
        "source",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=100),
        nullable=True,
    )
    op.alter_column(
        "trades",
        "transaction_type",
        existing_type=mysql.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "trades",
        "ticker",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "trades", "unrealized_holdings", ["holding_id"], ["id"])
    op.add_column(
        "unrealized_holdings", sa.Column("net_quantity", sa.Float(), nullable=False)
    )
    op.add_column(
        "unrealized_holdings", sa.Column("net_cost", sa.Float(), nullable=False)
    )
    op.add_column(
        "unrealized_holdings", sa.Column("last_trade_price", sa.Float(), nullable=False)
    )
    op.add_column(
        "unrealized_holdings",
        sa.Column("holding_period_days", sa.Integer(), nullable=True),
    )
    op.add_column(
        "unrealized_holdings", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.drop_column("unrealized_holdings", "total_holding")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "unrealized_holdings", sa.Column("total_holding", mysql.FLOAT(), nullable=False)
    )
    op.drop_column("unrealized_holdings", "updated_at")
    op.drop_column("unrealized_holdings", "holding_period_days")
    op.drop_column("unrealized_holdings", "last_trade_price")
    op.drop_column("unrealized_holdings", "net_cost")
    op.drop_column("unrealized_holdings", "net_quantity")
    op.drop_constraint(None, "trades", type_="foreignkey")
    op.alter_column(
        "trades",
        "ticker",
        existing_type=sa.String(length=10),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "trades",
        "transaction_type",
        existing_type=mysql.VARCHAR(length=10),
        nullable=False,
    )
    op.alter_column(
        "trades",
        "source",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "trades",
        "trade_type",
        existing_type=sa.String(length=50),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
