"""drop stop-loss

Revision ID: efa53c2719ad
Revises: cb25511c2eeb
Create Date: 2025-03-09 12:27:48.422442

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "efa53c2719ad"
down_revision = "cb25511c2eeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trades", "stop_loss")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trades", sa.Column("stop_loss", mysql.FLOAT(), nullable=True))
